# Generated by Django 6.1.1 on 2026-09-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('price_observations', models.PositiveSmallIntegerField(default=1)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_source', models.CharField(choices=[('census_place', 'Census place centroid'), ('census_county_subdivision', 'Census county subdivision centroid'), ('override', 'Station geocode override file'), ('none', 'Not geocoded')], default='none', max_length=30)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_lat_lon_idx')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('place', 'Census place'), ('county_subdivision', 'Census county subdivision')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('state', 'normalized_name'), name='unique_place_per_state')],
            },
        ),
    ]
